# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 218d6e0d3f8ef8e78ae047022558666781eb1dff90c4c81e0de61db6f368c3731d7440fc324006f8501fe639ba6ffeb71622d42463de2fc55c5e975dc5c5e361

test:
  secret_key_base: 3392da717e29975e5aa4cc431c6e70df3f339e5c06ecf2a28d197bcd4d68e1862e7f0d20c2a6b81d023b213f2288377c298e8471e8997aafd90ca717cabadb28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
